version: '3.8'

services:
  postgres:
    image: postgres:17.5-alpine
    container_name: ai_study_postgres
    environment:
      POSTGRES_DB: ai_study
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "15433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_study_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_study_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/ai_study
      DIFY_API_URL: ${DIFY_API_URL:-http://localhost:8080}
      DIFY_API_KEY: ${DIFY_API_KEY:-your_dify_api_key}
    ports:
      - "18000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - ai_study_network
    restart: unless-stopped

  frontend:
    build:
      context: ./backend_front
      dockerfile: Dockerfile
    container_name: ai_study_frontend
    ports:
      - "13000:3000"
    volumes:
      - ./backend_front:/app
      - /app/node_modules
    networks:
      - ai_study_network
    environment:
      - VITE_API_BASE_URL=http://localhost:18000

volumes:
  postgres_data:

networks:
  ai_study_network:
    driver: bridge