name: api_validator_plugin
description: Flutter API格式检查插件，集成到flutter analyze体系中
version: 1.0.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  analyzer_plugin: ^0.11.3
  path: ^1.8.0

dev_dependencies:
  test: ^1.21.0
  lints: ^2.0.0

# 插件配置
analyzer:
  plugins:
    - api_validator_plugin

# 插件入口点
executables:
  api_validator_plugin: plugin