"""Increase question title length limit to 2000 characters

Revision ID: 0550f48d2568
Revises: 891fa4825dfd
Create Date: 2025-07-26 03:08:22.763770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0550f48d2568'
down_revision = '891fa4825dfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###