"""Auto-generated model changes

Revision ID: 09085984cae7
Revises: 19626bf1e7ac
Create Date: 2025-07-24 05:43:40.907196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09085984cae7'
down_revision = '19626bf1e7ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('imported_questions', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_banks_id'), 'question_banks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_banks_id'), table_name='question_banks')
    op.drop_table('question_banks')
    # ### end Alembic commands ###