"""Auto-generated model changes

Revision ID: 0ce38af7a8ad
Revises: 200250775080
Create Date: 2025-07-26 04:58:14.239931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce38af7a8ad'
down_revision = '200250775080'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_bank_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'question_banks', ['question_bank_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'question_bank_id')
    # ### end Alembic commands ###