"""Change question title from String to Text type

Revision ID: 200250775080
Revises: c7f2441facd7
Create Date: 2025-07-26 03:09:45.545849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200250775080'
down_revision = 'c7f2441facd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###