"""Auto-generated model changes

Revision ID: 891fa4825dfd
Revises: fa6cc473aec6
Create Date: 2025-07-26 03:08:11.365802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891fa4825dfd'
down_revision = 'fa6cc473aec6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'title',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###