"""add_missing_foreign_keys_and_relationships

Revision ID: b39859c85155
Revises: 0ce38af7a8ad
Create Date: 2025-07-26 05:00:32.010159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39859c85155'
down_revision = '0ce38af7a8ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###