"""Auto-generated model changes

Revision ID: fa6cc473aec6
Revises: 09085984cae7
Create Date: 2025-07-25 12:57:53.473300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6cc473aec6'
down_revision = '09085984cae7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_banks', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question_banks', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_banks', type_='foreignkey')
    op.drop_column('question_banks', 'subject_id')
    # ### end Alembic commands ###